project:
  name: quickstart-chainlink-node
  regions:
  # only able to test in region with SSL certificates set up through AWS Certificate Manager
  - us-east-1
tests:
  default:
    template: ./templates/quickstart-chainlink-node-main.yml
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      KeyPairName: quickstart-staging
      ChainlinkNodeGUIPassword: 'TESTlink123!@_'
      NodeWalletPassword: 'TESTlink123!@_'
      DBMasterUserPassword: 'Docker_1234'
      SSLCertificateARN: 'arn:aws:acm:us-east-1:389435844244:certificate/8b0b7ba3-09f9-4101-875a-75236b2044bd'